baseURL : 
languageCode : id
title : devfan
params:
    description: Kumpulan tulisan berupa kode-kode aneh

staticDir: static

disqusShortname: fajars-space

tags: []

permalinks:
  dev : /:slug/
  
outputs:
    home : ["HTML", "RSS", "JSON"]
